dist: xenial
language: cpp
sudo: required
compiler: gcc -std=c++11
os: linux
install:
- sudo apt-get install libncurses5-dev
- touch test-config
- cd policies
- |
  for policy in *.cpp; do
    policy="$(echo $policy | cut -d'.' -f 1)"
    echo "$policy 32 32 1" >> ../test-config
  done
- cd ../
- cat test-config
script:
- ./run.sh -c test-config -t sample.out.gz -i